### ISSUE TITLE
Could not resolve host: geolite.maxmind.com

### ISSUE THREAD

**Issue by nikolaitarasov** [lexrus/MMDB-Swift#14]
Starting December 30, 2019, downloads will no longer be served from our public GeoLite2 page, from geolite.maxmind.com/download/geoip/database/*, or from any other public URL.
Please fix this as soon as possible. 
For more details: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by zhuhaow** [comment]
Looks like the only solution is to totally remove the bundled geolite2 database.

**Comment by nikolaitarasov** [comment]
I was able to fix the issue locally by following the steps provided in the link I posted in my original comment.

**Comment by zhuhaow** [comment]
It's not possible to do it without manual setup.

I'm leaning to removing the bundled database, so at least the framework works.

**Comment by dvovk** [comment]
the same stuff here, please fix it

**Comment by nikolaitarasov** [comment]
I updated the following line in the update_database.sh script:
curl -L -o $tmpfile "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=XXXXXXX&suffix=tar.gz"
To get license_key you need to sign up on maxmind website and create the key. After I did this everything works for me.

**Comment by zhuhaow** [comment]
I'm going to remove the bundled geolite2 database. The only thing is that this is a breaking change.

@nikolaitarasov We can't distribute geolite2 database with the framework.
