### ISSUE TITLE
Add package on Linux

### ISSUE THREAD

**Issue by sergeydi** [lexrus/MMDB-Swift#3]
Hi,
I have a problem during adding MMDB-Swift to linux(Ubuntu 16.04) swift(3.0.2) project:
Package.swift:
    import PackageDescription

    let package = Package(
        name: "Antiparsing_v3",
        targets: [],
        dependencies: [
            .Package(url: "https://github.com/lexrus/MMDB-Swift.git", versions: Version(0,0,1)..<Version(0,2,0)),
        ]
    )

When I try to build project, I get error:
$ swift build
warning: refname '0.0.2' is ambiguous.
warning: refname '0.0.2' is ambiguous.
HEAD is now at 7d14b1d Clean up.
Resolved version: 0.0.2
error: The package at `.../Packages/MMDB-Swift.git' has no Package.swift for the specific version: 0.0.2

**Comment by lexrus** [comment]
Oh, I forgot to add the Package.swift file. Now it's there in the master repo.
The latest tag is 0.2.2. Could you please try again?

**Comment by sergeydi** [comment]
My Package file:
import PackageDescription

let package = Package(
    name: "...",
    dependencies: [
    .Package(url: "https://github.com/lexrus/MMDB-Swift", versions: "0.0.1" ..< Version.max)
  ]
)

And I got error:
Package.swift:7:6: error: ambiguous reference to member 'Package'
    .Package(url: "https://github.com/lexrus/MMDB-Swift", versions: "0.0.1" ..< Version.max),
     ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/Dropbox/work_PC/Antiparsing_v3/Package.swift:7:6: note: overloads for 'Package' exist with these partially matching parameter lists: (url: String, versions: Range<Version>), (url: String, versions: ClosedRange<Version>)
    .Package(url: "https://github.com/lexrus/MMDB-Swift", versions: "0.0.1" ..< Version.max),
     ^
Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.
error: invalid manifest format

**Comment by sergeydi** [comment]
On Ubuntu 16.04 and swift 4.0.3:
dependencies: ["MMDB-Swift"]
$ swift build
error: invalid target name at 'MMDBTests'; name of non-test targets cannot end in 'Tests'
error: product dependency 'MMDB-Swift' not found

**Comment by bre7** [comment]
Working fork for SPM: https://github.com/bre7/MMDB-Swift

Thanks for the lib lexrus 👍👍👍 

To fix your repo, you need to specify the directory for each target since the folder structure is not the default for SPM (`Sources/*` and `Tests/*`)

**Comment by lexrus** [comment]
@bre7 Thank you. I'll update it soon.

**Comment by bre7** [comment]
There's no need to use the nio dependency. You can create your own linker package instead

**Comment by lexrus** [comment]
Please check out the latest release(0.2.9).
