### ISSUE TITLE
lost the file 'GeoLite2-Country.mmdb'

### ISSUE THREAD

**Issue by Jiar** [lexrus/MMDB-Swift#8]
![lost the file 'GeoLite2-Country.mmdb'](https://github.com/Jiar/ImageHosting/blob/master/Github/Issues/lost%20the%20file%20'GeoLite2-Country.mmdb'.jpeg?raw=true)

**Comment by zhuhaow** [comment]
Have you tried to compile it?

**Comment by Jiar** [comment]
I download the file 'GeoLite2-Country.mmdb' from [dev.maxmind.com](https://dev.maxmind.com/geoip/geoip2/geolite2/) to fix it.

@zhuhaow

**Comment by Jiar** [comment]
@zhuhaow

**Comment by zhuhaow** [comment]
Why are you all trying to build the demo?
Just build the framework you want to use.

**Comment by zhuhaow** [comment]
The framework should build just fine.

**Comment by zhuhaow** [comment]
Found the problem, the error happens if you build iOS framework first.

**Comment by Jiar** [comment]
you can see the target in picture, I am build the 'MMDB-iOS' framework.

@zhuhaow

**Comment by zhuhaow** [comment]
Fixed.
